version: '5.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:80"
      - "4444:4444"
    container_name: oneforfitcodeception_app